name: Ensure Modpack
description: Ensure Modpack
inputs:
  dir:
    description: Directory to download modpack
    required: true
  url:
    description: URL to download modpack
    required: true
  name:
    description: Name of modpack
    required: true

runs:
  using: composite
  steps:
    - id: cache-modpack
      uses: actions/cache@v3
      with:
        path: ${{ inputs.dir }}/${{ inputs.name }}
        key: ${{ inputs.url }}
    - if: steps.cache-modpack.outputs.cache-hit != 'true'
      shell: bash
      working-directory: ${{ inputs.dir }}
      run: |
        wget -O ${{ inputs.name }}.zip ${{ inputs.url }}
        unzip -o ${{ inputs.name }}.zip -d ${{ inputs.name }}
